n = int(input())
w = list(map(str,input().split()))
target_words=set(["and","not","that","the","you"])
 
for i in w:
  if(i in target_words):
    print("Yes")
    exit()
print("No")

# #Generated by ChatGPT4 and Edited by kibutan
# def main():
#   N = int(input())
#   words = list(map(str,input().split()))
#   target_words = {'and', 'not', 'that', 'the', 'you'}
#   for word in words:
#     if word in target_words:
#       print('Yes')
#       return
#   print('No')
 
# main()
